apiVersion: "v1"
kind: "Service"
metadata:
  name: "pdf-service-ui-service"
  namespace: "default"
  labels:
    app: "pdf-service-ui"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: "pdf-service"
  type: "LoadBalancer"
